export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const PHONE_PLANS_REPOSITORY = 'PHONE_PLANS_REPOSITORY';
export const RATE_REPOSITORY = 'RATE_REPOSITORY';
export const PRICE_REPORT_REPOSITORY = 'PRICE_REPORT_REPOSITORY';
